name: Linting

on:
  push:
    branches: [master, main, develop]
  pull_request:
    branches: [master, main, develop]

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install PNPM
        run: npm i pnpm@latest -g

      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Setup PNPM config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install dependencies
        run: pnpm install

      - name: Get File Changes
        id: get_files_changed
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ' '

      - name: File(s) Changed
        run: |
          echo Added files: ${{ steps.get_files_changed.outputs.files_added }}
          echo Changed files: ${{ steps.get_files_changed.outputs.files_modified }}
          echo Removed files: ${{ steps.get_files_changed.outputs.files_removed }}

      - name: Run ESlint
        if: ${{ always() && (steps.get_file_changes.outputs.files_added || steps.get_file_changes.outputs.files_modified) }}
        run: yarn eslint --config ./eslintrc.js -e "**/*.(ts|tsx|js|jsx|css|scss|html|md|json|yml)" ${{ steps.get_file_changes.outputs.files_added }} ${{ steps.get_file_changes.outputs.files_modified }} --fix

      - name: Commit Lint Fixes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Apply ESLint and StyleLint formatting changes
