name: Testing

on:
  pull_request:
    branches: [main, develop]

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  testing:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3

      - name: Set Up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: pnpm install

      - name: Run Jest
        run: pnpm test:jest
